In [526]:
import numpy as np

In [527]:
# Original matrix
original_matrix = np.array([[10, 20, 30],
                            [40, 50, 60],
                            [70, 80, 90],
                            [100, 110, 120]])

# List of row indices to select from the original matrix
# For example, select row at index 0, then row at index 2, then row at index 0 again
selected_indices = np.array([0, 2, 0, 1, 3, 3])

# Create the new array by selecting rows based on the indices
# This creates a new array where each row corresponds to the selected row from original_matrix
new_array = original_matrix[selected_indices]

print("Original Matrix:")
print(original_matrix)
print("\nSelected Indices:")
print(selected_indices)
print("\nNew Array (rows copied based on indices):")
print(new_array)

Original Matrix:
[[ 10  20  30]
 [ 40  50  60]
 [ 70  80  90]
 [100 110 120]]

Selected Indices:
[0 2 0 1 3 3]

New Array (rows copied based on indices):
[[ 10  20  30]
 [ 70  80  90]
 [ 10  20  30]
 [ 40  50  60]
 [100 110 120]
 [100 110 120]]


In [528]:
# Define the specific row indices you want for *each corresponding column*
# The length of this index array should match the number of columns in 'original_matrix'
row_indices = np.array([0, 1, 3,]) # Get element at (0, 0), (1, 1), (2, 2), (3, 3)

# Define the column indices. We can use np.arange for this.
col_indices = np.arange(original_matrix.shape[1])

# Use advanced indexing to select the elements
# arr[row_indices, col_indices]
selected_elements = original_matrix[row_indices, col_indices]

print("\nSelected Elements:")
print(selected_elements)


Selected Elements:
[ 10  50 120]


## Solution

In [529]:
m = np.random.randint(2, 10)   
p = np.random.randint(2, 10) 
n = np.random.randint(2, 10)   

Q = np.random.randint(-20, 21, size=(m, p))
X = np.random.randint(-20, 21, size=(n, p))

print(f"\nQ: shape:({m},{p})")
print(Q)

print(f"\nX: shape:({n},{p})")
print(X)



Q: shape:(3,6)
[[-19  13 -11  13  17 -10]
 [  8   2  -5 -17  10  -2]
 [ -4  -9  -6  -3   4  -1]]

X: shape:(2,6)
[[  9  -2  14   8  -7  13]
 [  9   7  17   7 -16   9]]


In [530]:
dist = np.sum((Q[:, None, :] - X[None, :, :])**2, axis=2) # (m,n), dist[i,j]:=distance b/w Q[i] and X[j].

print(f"\ndist: shape:{dist.shape}")
print(dist)


dist: shape:(3, 2)
[[2764 3090]
 [1517 1883]
 [1056 1554]]


In [531]:
minq_ind = np.argmin(dist, axis=0) #(n,), row index of row vector of Q that has smallest distance from ith row vector of X

print("\nminq_ind:")
print(minq_ind)


minq_ind:
[2 2]


In [532]:
type(minq_ind) #np.min returns an nparray

numpy.ndarray

In [533]:
qhat = Q[minq_ind] #(n.p), qhat[i] = Q[minq_ind[i]]

print(f"\nQ: shape:({m},{p})")
print(Q)

print(f"\nqhat: shape{qhat.shape}")
print(qhat)

print(f"\nX: shape:({n},{p})")
print(X)


Q: shape:(3,6)
[[-19  13 -11  13  17 -10]
 [  8   2  -5 -17  10  -2]
 [ -4  -9  -6  -3   4  -1]]

qhat: shape(2, 6)
[[-4 -9 -6 -3  4 -1]
 [-4 -9 -6 -3  4 -1]]

X: shape:(2,6)
[[  9  -2  14   8  -7  13]
 [  9   7  17   7 -16   9]]


In [534]:
col_ind = np.arange(dist.shape[1]) # (n,)
dhat = dist[minq_ind, col_ind] # (n,), select minimum distances

print(f"\ndhat: shape{dhat.shape}")
print(dhat.reshape(-1,1))


dhat: shape(2,)
[[1056]
 [1554]]


### part(b)

In [535]:
A = np.hstack((np.sqrt(dhat).reshape(-1,1),qhat)) # (n,p+1)

print(f"\nA: shape{A.shape}")
print(A)


A: shape(2, 7)
[[32.49615362 -4.         -9.         -6.         -3.          4.
  -1.        ]
 [39.42080669 -4.         -9.         -6.         -3.          4.
  -1.        ]]


In [536]:
y = np.random.randint(-20, 21, (n)) #(n,)

print(f"\ny: shape{y.reshape(-1,1).shape}")
print(y.reshape(-1,1))


y: shape(2, 1)
[[ 3]
 [17]]


In [537]:
beta = np.linalg.lstsq(A,y) # (p+1,)

desc = ['lstsq soln','residuals','rank','singular values']
for i in range(len(beta)):
    print("\n" + desc[i] + ":")
    print(beta[i])


lstsq soln:
[ 2.02176194  1.57734557  3.54902754  2.36601836  1.18300918 -1.57734557
  0.39433639]

residuals:
[]

rank:
2

singular values:
[54.08690963  1.61437497]


In [538]:
alpha = beta[0][0]
w = beta[0][1:]

print(f"\nalpha: shape{alpha.shape}")
print(alpha)

print(f"\nw: shape{w.reshape(-1,1).shape}")
print(w.reshape(-1,1))


alpha: shape()
2.0217619363525534

w: shape(6, 1)
[[ 1.57734557]
 [ 3.54902754]
 [ 2.36601836]
 [ 1.18300918]
 [-1.57734557]
 [ 0.39433639]]
