In [1]:
import numpy as np

In [2]:
# Original matrix
original_matrix = np.array([[10, 20, 30],
                            [40, 50, 60],
                            [70, 80, 90],
                            [100, 110, 120]])

# List of row indices to select from the original matrix
# For example, select row at index 0, then row at index 2, then row at index 0 again
selected_indices = np.array([0, 2, 0, 1, 3, 3])

# Create the new array by selecting rows based on the indices
# This creates a new array where each row corresponds to the selected row from original_matrix
new_array = original_matrix[selected_indices]

print("Original Matrix:")
print(original_matrix)
print("\nSelected Indices:")
print(selected_indices)
print("\nNew Array (rows copied based on indices):")
print(new_array)

Original Matrix:
[[ 10  20  30]
 [ 40  50  60]
 [ 70  80  90]
 [100 110 120]]

Selected Indices:
[0 2 0 1 3 3]

New Array (rows copied based on indices):
[[ 10  20  30]
 [ 70  80  90]
 [ 10  20  30]
 [ 40  50  60]
 [100 110 120]
 [100 110 120]]


In [3]:
# Define the specific row indices you want for *each corresponding column*
# The length of this index array should match the number of columns in 'original_matrix'
row_indices = np.array([0, 1, 3,]) # Get element at (0, 0), (1, 1), (2, 2), (3, 3)

# Define the column indices. We can use np.arange for this.
col_indices = np.arange(original_matrix.shape[1])

# Use advanced indexing to select the elements
# arr[row_indices, col_indices]
selected_elements = original_matrix[row_indices, col_indices]

print("\nSelected Elements:")
print(selected_elements)


Selected Elements:
[ 10  50 120]


## Solution

In [46]:
m = np.random.randint(2, 10)   
p = np.random.randint(2, 10) 
n = np.random.randint(2, 10)   

Q = np.random.randint(-20, 21, size=(m, p))
X = np.random.randint(-20, 21, size=(n, p))

print(f"\nQ: shape:({m},{p})")
print(Q)

print(f"\nX: shape:({n},{p})")
print(X)



Q: shape:(2,9)
[[-12  16 -17 -14  -3 -11  -4  13 -18]
 [-20  12   8   1   3 -19 -19   7   2]]

X: shape:(5,9)
[[ -6  -8  13  15  10  12 -13  -4 -11]
 [  4   2  10 -13 -14 -17 -10 -11   0]
 [-17  12  -1  10   1   0   6   5  -2]
 [ 14   0 -18  -2  -8 -20  13  20  -5]
 [-13   7  14  -5  16 -18  17  17  12]]


In [47]:
dist = np.sum((Q[:, None, :] - X[None, :, :])**2, axis=2) # (m,n), dist[i,j]:=distance b/w Q[i] and X[j].

print(f"\ndist: shape:{dist.shape}")
print(dist)


dist: shape:(2, 5)
[[3470 2275 1430 1690 2891]
 [2153 1578 1181 3349 1812]]


In [48]:
minq_ind = np.argmin(dist, axis=0) #(n,), row index of row vector of Q that has smallest distance from ith row vector of X

print("\nminq_ind:")
print(minq_ind)


minq_ind:
[1 1 1 0 1]


In [49]:
type(minq_ind) #np.min returns an nparray

numpy.ndarray

In [50]:
qhat = Q[minq_ind] #(n.p), qhat[i] = Q[minq_ind[i]]

print(f"\nqhat: shape{qhat.shape}")
print(qhat)

print(f"\nQ: shape:({m},{p})")
print(Q)

print(f"\nX: shape:({n},{p})")
print(X)


qhat: shape(5, 9)
[[-20  12   8   1   3 -19 -19   7   2]
 [-20  12   8   1   3 -19 -19   7   2]
 [-20  12   8   1   3 -19 -19   7   2]
 [-12  16 -17 -14  -3 -11  -4  13 -18]
 [-20  12   8   1   3 -19 -19   7   2]]

Q: shape:(2,9)
[[-12  16 -17 -14  -3 -11  -4  13 -18]
 [-20  12   8   1   3 -19 -19   7   2]]

X: shape:(5,9)
[[ -6  -8  13  15  10  12 -13  -4 -11]
 [  4   2  10 -13 -14 -17 -10 -11   0]
 [-17  12  -1  10   1   0   6   5  -2]
 [ 14   0 -18  -2  -8 -20  13  20  -5]
 [-13   7  14  -5  16 -18  17  17  12]]


In [51]:
col_ind = np.arange(dist.shape[1]) # (n,)
dhat = dist[minq_ind, col_ind] # (n,), select minimum distances

print(f"\ndhat: shape{dhat.shape}")
print(dhat.reshape(-1,1))


dhat: shape(5,)
[[2153]
 [1578]
 [1181]
 [1690]
 [1812]]


### part(b)

In [52]:
A = np.hstack((np.sqrt(dhat).reshape(-1,1),qhat)) # (n,p+1)

print(f"\nA: shape{A.shape}")
print(A)


A: shape(5, 10)
[[ 46.40043103 -20.          12.           8.           1.
    3.         -19.         -19.           7.           2.        ]
 [ 39.72404813 -20.          12.           8.           1.
    3.         -19.         -19.           7.           2.        ]
 [ 34.36568055 -20.          12.           8.           1.
    3.         -19.         -19.           7.           2.        ]
 [ 41.10960958 -12.          16.         -17.         -14.
   -3.         -11.          -4.          13.         -18.        ]
 [ 42.56759331 -20.          12.           8.           1.
    3.         -19.         -19.           7.           2.        ]]


In [53]:
y = np.random.randint(-20, 21, (n)) #(n,)

print(f"\ny: shape{y.reshape(-1,1).shape}")
print(y.reshape(-1,1))


y: shape(5, 1)
[[ 15]
 [-13]
 [ -4]
 [-18]
 [ 11]]


In [54]:
beta = np.linalg.lstsq(A,y) # (p+1,)

desc = ['lstsq soln','residuals','rank','singular values']
for i in range(len(beta)):
    print("\n" + desc[i] + ":")
    print(beta[i])


lstsq soln:
[ 1.86254447  1.21629821 -1.16581303  0.59365613  0.66260532  0.05539206
  1.13566356  0.78881825 -0.86173848  0.82971733]

residuals:
[]

rank:
3

singular values:
[1.19090765e+02 3.60297835e+01 5.40781187e+00 1.66530926e-15
 2.26971322e-16]


In [55]:
alpha = beta[0][0]
w = beta[0][1:]

print(f"\nalpha: shape{alpha.shape}")
print(alpha)

print(f"\nw: shape{w.shape}")
print(w)


alpha: shape()
1.8625444719482185

w: shape(9,)
[ 1.21629821 -1.16581303  0.59365613  0.66260532  0.05539206  1.13566356
  0.78881825 -0.86173848  0.82971733]
