In [2]:
import numpy as np

In [44]:
a = np.array([[1, 2, 3],
              [4, 5, 6]])   # shape (2, 3)
b = np.array([[10, 20, 30, 40, 50]])  # shape (1, 5)

#print(a + b)


## BroadCasting

In [45]:

test = np.array([[[[2],[6]]], [[[2],[6]]], [[[2],[6]]]])
test2 = np.array([[[8,-1]],[[8,-1]],[[8,-1]]])

print(test.shape)
print(test2.shape)


(3, 1, 2, 1)
(3, 1, 2)


In [46]:
C = np.array([2, 2])
D = np.array([[8],[-1]])

print(C*D)

[[16 16]
 [-2 -2]]


In [47]:
print(test*test2)

[[[[16 -2]
   [48 -6]]

  [[16 -2]
   [48 -6]]

  [[16 -2]
   [48 -6]]]


 [[[16 -2]
   [48 -6]]

  [[16 -2]
   [48 -6]]

  [[16 -2]
   [48 -6]]]


 [[[16 -2]
   [48 -6]]

  [[16 -2]
   [48 -6]]

  [[16 -2]
   [48 -6]]]]


## Dimensions (tensors)

In [48]:
square = np.array([[[[1, 1],[1,1]], [[1, 1],[1,1]]],[[[1, 1],[1,1]], [[1, 1],[1,1]]]])
print(square)
print(square.shape)

[[[[1 1]
   [1 1]]

  [[1 1]
   [1 1]]]


 [[[1 1]
   [1 1]]

  [[1 1]
   [1 1]]]]
(2, 2, 2, 2)


In [49]:
a = np.array(1)
b = np.array([1])
c = np.array([[1]])
d = np.array([[[1]]])
print(a.shape, b.shape, c.shape, d.shape)

() (1,) (1, 1) (1, 1, 1)


## using `np.sum`

In [6]:
a = np.array([[1,2],[3,4],[5,6]])
print(np.sum(a, axis=1))


[ 3  7 11]


## Generate random 4 row array:

In [51]:
num_col = np.random.randint(5,25)
A = np.arange(1, 4*num_col + 1).reshape(4, num_col)
print(A)

[[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38]
 [39 40 41 42 43 44 45 46 47 48 49 50 51 52 53 54 55 56 57]
 [58 59 60 61 62 63 64 65 66 67 68 69 70 71 72 73 74 75 76]]


## For loop review:

In [52]:
for i in range(7):
    print('check', i)

check 0
check 1
check 2
check 3
check 4
check 5
check 6


## summing tensor by axis:

In [53]:
X = np.arange(1,13).reshape(1,3,2,2)
print(X)

[[[[ 1  2]
   [ 3  4]]

  [[ 5  6]
   [ 7  8]]

  [[ 9 10]
   [11 12]]]]


In [54]:
print(np.sum(X,axis=0))

[[[ 1  2]
  [ 3  4]]

 [[ 5  6]
  [ 7  8]]

 [[ 9 10]
  [11 12]]]


In [55]:
print(np.sum(X,axis=1))

[[[15 18]
  [21 24]]]


In [56]:
print(np.sum(X,axis=2))

[[[ 4  6]
  [12 14]
  [20 22]]]


In [57]:
print(np.sum(X,axis=3))

[[[ 3  7]
  [11 15]
  [19 23]]]


## Reshaping:

In [44]:
a = np.arange(5)
print(a)
print(a.shape)
print(a[None,:])
print((a[None,:]).shape)
print(a[:,None])
print((a[:,None]).shape)

[0 1 2 3 4]
(5,)
[[0 1 2 3 4]]
(1, 5)
[[0]
 [1]
 [2]
 [3]
 [4]]
(5, 1)


In [45]:
print(a.reshape(5,1))
print((a.reshape(5,1)).shape)

[[0]
 [1]
 [2]
 [3]
 [4]]
(5, 1)


In [15]:
b = a[:,None]
print(b)
print(b.shape)
b = b[None,:]
print(b)
print(b.shape)

[[0]
 [1]
 [2]
 [3]
 [4]]
(5, 1)
[[[0]
  [1]
  [2]
  [3]
  [4]]]
(1, 5, 1)


**Note** 

Every time you use [None,:] or [:,None], you are adding a new (higher) dimension to your original array

But not if you are using reshape()

In [20]:
print('a = ', a)
c = a.reshape(5,1)
print(c)
print(c.shape)
c = c.reshape(1,5)
print(c)
print(c.shape)

a =  [0 1 2 3 4]
[[0]
 [1]
 [2]
 [3]
 [4]]
(5, 1)
[[0 1 2 3 4]]
(1, 5)


## Adding new dimension:

In [59]:
X = np.arange(6).reshape(3,2)
X

array([[0, 1],
       [2, 3],
       [4, 5]])

In [60]:
X[:, :, None]

array([[[0],
        [1]],

       [[2],
        [3]],

       [[4],
        [5]]])

## Latex

### Keyboard shortcut to add markdown: (B) for below + (M) for Markdown.

$$y_i = \beta_0 + \beta_1 x_{i1} + \beta_2 x_{i2} + \epsilon_i$$

$$X = \begin{pmatrix} 1 & x_{11} & x_{12} \\ 1 & x_{21} & x_{22} \\ 1 & x_{31} & x_{32} \\ 1 & x_{41} & x_{42} \end{pmatrix}$$

$$X = \begin{pmatrix} 1 & 0 & 1 \\ 1 & 2 & 3 \\ 1 & 4 & 8 \\ 1 & 6 & 10 \end{pmatrix}$$

$$\mathbf{y} = \begin{pmatrix} 3.0 \\ 5.0 \\ 9.0 \\ 10.0 \end{pmatrix} ,  \mathbf{\beta} = \begin{pmatrix} \beta_0 \\ \beta_1 \\ \beta_2 \end{pmatrix}$$

$$\mathbf{\beta} = (X^T X)^{-1} X^T \mathbf{y}$$

$$\mathbf{X} = \begin{pmatrix} 1 & 0 & 1 \\ 1 & 2 & 3 \\ 1 & 4 & 8 \\ 1 & 6 & 10 \end{pmatrix}$$

In [61]:
dtest = np.arange(1,11)
dtest_1 = np.array(range(1,11))

In [62]:
dtest

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [63]:
dtest_1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [64]:
u = np.arange(1,20,2)
print(u)
x = np.zeros(len(u))
print(x)
print(np.ones(len(u))*np.exp(1))

[ 1  3  5  7  9 11 13 15 17 19]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[2.71828183 2.71828183 2.71828183 2.71828183 2.71828183 2.71828183
 2.71828183 2.71828183 2.71828183 2.71828183]


In [71]:
d = 1
r = u * np.arange(d+1)[:, None]
y_hat = np.exp((u * np.arange(d+1)[:, None])/-d)
print(r)
print(y_hat)
print(np.sum(y_hat,axis=0))
print(u)

[[ 0  0  0  0  0  0  0  0  0  0]
 [ 1  3  5  7  9 11 13 15 17 19]]
[[1.00000000e+00 1.00000000e+00 1.00000000e+00 1.00000000e+00
  1.00000000e+00 1.00000000e+00 1.00000000e+00 1.00000000e+00
  1.00000000e+00 1.00000000e+00]
 [3.67879441e-01 4.97870684e-02 6.73794700e-03 9.11881966e-04
  1.23409804e-04 1.67017008e-05 2.26032941e-06 3.05902321e-07
  4.13993772e-08 5.60279644e-09]]
[1.36787944 1.04978707 1.00673795 1.00091188 1.00012341 1.0000167
 1.00000226 1.00000031 1.00000004 1.00000001]
[ 1  3  5  7  9 11 13 15 17 19]


## kfold validation python scratch

In [4]:
from sklearn.model_selection import KFold

Xdly = np.arange(12).reshape(12, 1)  # dummy data
kf = KFold(n_splits=3, shuffle=True, random_state=0)

for isplit, Ind in enumerate(kf.split(Xdly)):
    train_index, test_index = Ind
    print(f"Split {isplit}:")
    print("  Train indices:", train_index)
    print("  Test indices:", test_index)

Split 0:
  Train indices: [0 1 2 3 5 7 8 9]
  Test indices: [ 4  6 10 11]
Split 1:
  Train indices: [ 0  3  4  5  6  9 10 11]
  Test indices: [1 2 7 8]
Split 2:
  Train indices: [ 1  2  4  6  7  8 10 11]
  Test indices: [0 3 5 9]


## simple one vector train test split

In [64]:
from sklearn.model_selection import train_test_split
x = np.linspace(1,200,100)
y = np.logspace(1,3,100)
print(x)
print(y)

[  1.           3.01010101   5.02020202   7.03030303   9.04040404
  11.05050505  13.06060606  15.07070707  17.08080808  19.09090909
  21.1010101   23.11111111  25.12121212  27.13131313  29.14141414
  31.15151515  33.16161616  35.17171717  37.18181818  39.19191919
  41.2020202   43.21212121  45.22222222  47.23232323  49.24242424
  51.25252525  53.26262626  55.27272727  57.28282828  59.29292929
  61.3030303   63.31313131  65.32323232  67.33333333  69.34343434
  71.35353535  73.36363636  75.37373737  77.38383838  79.39393939
  81.4040404   83.41414141  85.42424242  87.43434343  89.44444444
  91.45454545  93.46464646  95.47474747  97.48484848  99.49494949
 101.50505051 103.51515152 105.52525253 107.53535354 109.54545455
 111.55555556 113.56565657 115.57575758 117.58585859 119.5959596
 121.60606061 123.61616162 125.62626263 127.63636364 129.64646465
 131.65656566 133.66666667 135.67676768 137.68686869 139.6969697
 141.70707071 143.71717172 145.72727273 147.73737374 149.74747475
 151.7575757

In [37]:
'''Run for reshaping x and y
x = x[:,None]
print(x.shape)

y = y[:,None]
print(y.shape)
'''

'Run for reshaping x and y\nx = x[:,None]\nprint(x.shape)\n\ny = y[:,None]\nprint(y.shape)\n'

In [65]:
xtr, xts, ytr, yts = train_test_split(x,y,test_size=0.1)
print(xts)
print(yts)

[153.76767677 173.86868687  51.25252525 181.90909091 171.85858586
 157.78787879  67.33333333  87.43434343  91.45454545   3.01010101]
[343.04692863 546.22772177  31.99267138 657.93322466 521.4008288
 376.49358068  46.41588834  73.90722034  81.11308308  10.47615753]


### Testing broadcasting with redundant dimensions (using xts and yts)

In [66]:
xts.shape, yts.shape

((10,), (10,))

In [67]:
xts = (xts[None,:])[:,None] # want to make into column vector
yts = (yts[None,:])[None,:] # want to make into row vector

xts.shape,yts.shape

((1, 1, 10), (1, 1, 10))

In [68]:
zts = xts * yts
zts # we still get a vector inside an array that is inside an array, not a 2D array

array([[[5.27495292e+04, 9.49718967e+04, 1.63970520e+03, 1.19684035e+05,
         8.96072091e+04, 5.94061235e+04, 3.12533648e+03, 6.46202929e+03,
         7.41816014e+03, 3.15342924e+01]]])

**Note**

When we do `xts[None,:]`, assuming `xts` is of shape `(10,)` at start, we make `xts` of shape `(1,10)` as expected. But, when we run `[:,None]` on `xts` immediatedly afterwards, `xts` is now a `(1,1,10)` array because we are treating **the entire `(1,10)` array as one element** and putting it in a single dimension array with one column.

Use `reshape()` instead to broadcast properly

In [69]:
print(xts)

[[[153.76767677 173.86868687  51.25252525 181.90909091 171.85858586
   157.78787879  67.33333333  87.43434343  91.45454545   3.01010101]]]


In [70]:
print(yts)

[[[343.04692863 546.22772177  31.99267138 657.93322466 521.4008288
   376.49358068  46.41588834  73.90722034  81.11308308  10.47615753]]]


### trying to get (1,10,1)

In [71]:
v = np.arange(0,10)
v.shape

(10,)

In [72]:
v = v[:,None][None,:]
print(v)
print(v.shape)

[[[0]
  [1]
  [2]
  [3]
  [4]
  [5]
  [6]
  [7]
  [8]
  [9]]]
(1, 10, 1)


**Note**

`(1,10)` is technically a `(10,)` inside an array with one row and one column because we are treating the entire `(10,)` as one element

`:` means get every element, but the only element there is is the `(10,)` array

In [ ]:
t = np.arange(0,10)
print(t)
print(t.shape)
t = t[None,:] # get every element and put it in a new row
print(t)
print(t.shape)

[0 1 2 3 4 5 6 7 8 9]
(10,)
[[0 1 2 3 4 5 6 7 8 9]]
(1, 10)


## Using reshape:


In NumPy, reshape(-1, 1) is a method used to change the shape of an array.

    -1: This acts as a wildcard. When used in reshape, it tells NumPy to automatically calculate the size of that dimension based on the total number of elements in the array and the sizes of the other specified dimensions.
    1: This explicitly sets the size of the second dimension (columns) to 1. 

Therefore, array.reshape(-1, 1) reshapes a 1-D array into a 2-D array with a single column. The number of rows will be automatically determined by NumPy to accommodate all elements from the original array.

In [81]:
s = np.arange(0,10)
print(s.reshape(-1,1))
print(s.reshape(-1,1).ravel())

[[0]
 [1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]
 [9]]
[0 1 2 3 4 5 6 7 8 9]
