In [1]:
import numpy as np
from sklearn import linear_model
from sklearn.metrics import r2_score

In [2]:
A = np.array([[0,1,0,2],[0,1,0,3],[1,0,-1,0],[1,0,0,0]])
y = np.array([19,26,7,2])#.reshape(-1,1)

In [3]:
linreg = linear_model.LinearRegression(fit_intercept=False)
linreg.fit(A,y)

LinearRegression(fit_intercept=False)

In [4]:
linreg.coef_

array([ 2.,  5., -5.,  7.])

In [5]:
linreg.intercept_

0.0

In [6]:
A_inv = np.linalg.inv(A)

In [7]:
print(A_inv)

[[ 0.  0.  0.  1.]
 [ 3. -2.  0.  0.]
 [ 0.  0. -1.  1.]
 [-1.  1. -0. -0.]]


In [8]:
A

array([[ 0,  1,  0,  2],
       [ 0,  1,  0,  3],
       [ 1,  0, -1,  0],
       [ 1,  0,  0,  0]])

In [9]:
col_ones = np.ones((4,1))
padded_A = np.hstack((col_ones,A))

In [10]:
padded_A

array([[ 1.,  0.,  1.,  0.,  2.],
       [ 1.,  0.,  1.,  0.,  3.],
       [ 1.,  1.,  0., -1.,  0.],
       [ 1.,  1.,  0.,  0.,  0.]])

In [11]:
aTa = padded_A.T.dot(padded_A)

In [12]:
aTa # aTa is not actually invertible

array([[ 4.,  2.,  2., -1.,  5.],
       [ 2.,  2.,  0., -1.,  0.],
       [ 2.,  0.,  2.,  0.,  5.],
       [-1., -1.,  0.,  1.,  0.],
       [ 5.,  0.,  5.,  0., 13.]])

In [13]:
np.linalg.det(aTa)

np.float64(-1.1102230246251573e-16)

In [14]:
from sympy import Matrix
aTa_matrix = Matrix(aTa)

In [15]:
rref_form, pivot_columns = aTa_matrix.rref()
print(rref_form)
print('pivot columns: ', pivot_columns)

Matrix([[1, 0, 1.00000000000000, 0, 0], [0, 1, -1.00000000000000, 0, 0], [0, 0, 0, 1, 0], [0, 0, 0, 0, 1], [0, 0, 0, 0, 0]])
pivot columns:  (0, 1, 3, 4)


In [ ]:
print(aTa_matrix.det()) # Matrix from sympy package does determinant correctly, not numpy.linalg

0


In [16]:
np.linalg.inv(aTa)

array([[-9.00719925e+15,  9.00719925e+15,  9.00719925e+15,
         0.00000000e+00, -5.00000000e+00],
       [ 9.00719925e+15, -9.00719925e+15, -9.00719925e+15,
         1.00000000e+00,  5.00000000e+00],
       [ 9.00719925e+15, -9.00719925e+15, -9.00719925e+15,
        -0.00000000e+00, -0.00000000e+00],
       [ 0.00000000e+00,  1.00000000e+00,  0.00000000e+00,
         2.00000000e+00,  0.00000000e+00],
       [-5.00000000e+00,  5.00000000e+00, -0.00000000e+00,
        -0.00000000e+00,  2.00000000e+00]])

In [17]:
# inverting zero matrix (not possible)
np.linalg.inv(np.array([[2,4],[1,2]]))

LinAlgError: Singular matrix

**Note**

Padding your design matrix with a column of ones is not a requirement, nor is removing the mean from it. You do this when you want to include an intercept in your linear model.

For the following two methods:
1) padding design matrix with a colum of ones
2) subtracting the mean of each column of the design matrix from each element and doing the same with the output matrix

Both methods give the same coefficient results except for the intercept because the intercept is not calculated for method `2`. (I don't know mathematical proof for yet)

If the calculated coefficient matrix from method `1` has dimensions `n x 1`, that of method `2` is `(n-1) x 1`, excluding the intercept at the first element (row 1 column 1)


$$\vec{β_{padded}} = \begin{pmatrix} \beta_0 \\ \beta_1 \\ \vdots \\ \beta_p \end{pmatrix} ,  \vec{β_{noMean}} = \begin{pmatrix} \beta_1 \\ \beta_2 \\ \vdots \\ \beta_p \end{pmatrix}$$
