# Numpy Array Operations:  Axes and Broadcasting 

There is an excellent introduction to `numpy` multi-dimensional arrays on the [scipy](https://docs.scipy.org/doc/numpy-dev/user/quickstart.html) website.  In this note, we cover two concepts in a little more detail:
* Using the `axis` feature 
* Python broadcasting

We will need both of these for performing many of the numerical operations for the ML class.

As usual, we begin by loading the `numpy` package.

In [1]:
import numpy as np

## Axis Parameter

Many operations in the `numpy` package can take an optional `axis` parameter to specify which dimensions the operation is to be applied.  This is extremely useful for multi-dimensional data.  To illustrate the `axis` parameter, consider a matrix the `(3,2)` array `X` defined as:

In [12]:
X = np.arange(6).reshape(3,2)
print(X)

[[0 1]
 [2 3]
 [4 5]]


An operation like `np.mean` or `np.sum` takes the mean or sum of *all* elements in the array. 

In [13]:
print(np.mean(X))
print(np.sum(X))

2.5
15


To take only the `sum` along each column, we can use the `axis` parameter.

In [14]:
print(np.sum(X,axis=0))

[6 9]


In [15]:
print(np.shape(X))

(3, 2)


Note: take the mean of each column of `X`:

In [16]:
print(np.mean(X, axis=0))

[2. 3.]


Note: python code for printing out the dimensions of matrix X below:

In [17]:
print(np.shape(np.sum(X, axis=0)))

(2,)


Since `X` has shape `(3,2)`, the output `np.sum(X,axis=0)` is of shape `(2,)`.  Similarly, we can take the `sum` along each row:

In [18]:
print(np.sum(X,axis=1))

[1 5 9]


You can apply this to higher-order arrays:

In [19]:
X = np.arange(24).reshape(2,3,4)  # shape = (2,3,4)
Y1 = np.sum(X,axis=0)             # shape = (3,4)
Y2 = np.sum(X,axis=1)             # shape = (2,4)
print('Y1 = ')
print(Y1)
print('Y2 = ')
print(Y2)

Y1 = 
[[12 14 16 18]
 [20 22 24 26]
 [28 30 32 34]]
Y2 = 
[[12 15 18 21]
 [48 51 54 57]]


In [20]:
print(X)

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


Note: what if the number of elements to be arranged is not the same as the available space in matrix?
An error will be thrown

In [21]:
Mtrx = np.arange(20).reshape(2,3,4)
print(Mtrx)

ValueError: cannot reshape array of size 20 into shape (2,3,4)

## Broadcasting

**Broadcasting** is a powerful tool in Python for performing operations on matrices that we will use throughout the ML class.  A good tutorial on broadcasting can be found on the [scipy broadcasting page](https://docs.scipy.org/doc/numpy-1.13.0/user/basics.broadcasting.html).  Here we provide some examples.   

### Example 1:  Mean Removal

Suppose that `X` is a data matrix of shape `(n,p)`.  That is, there are `n` data points and `p` features per point.  Often, we have to remove the mean from each feature.  That is, we want to compute the mean for each feature and then remove the mean from each column.  We could do this with a for-loop as:
   
    Xm = np.zeros(p)      # Mean for each feature
    X1_demean = np.zeros((n,p))  # Transformed features with the means removed
    for j in range(p):
       Xm[j] = np.mean(X[:,j])
       for i in range(n):
           X_demean[i,j] = X[i,j] - Xm[j]
           
The code below does this without a for loop using the `axis` parameter and broadcasting.

In [25]:
# Generate some random data
n = 100
p = 5
X = np.random.rand(n,p)

# Compute the mean per column using the axis command
Xm = np.mean(X,axis=0)  # This is a p-dim matrix

# Subtract the mean
X_demean = X - Xm[None,:]

In [27]:
print(X)

[[0.21223333 0.77175082 0.1578439  0.12005405 0.4816153 ]
 [0.57598394 0.1958655  0.18947995 0.23823771 0.60386571]
 [0.24477615 0.77952675 0.26401113 0.74927777 0.05618032]
 [0.53990138 0.800736   0.19352144 0.61094074 0.47839642]
 [0.5367433  0.51839468 0.93067253 0.28051617 0.7796864 ]
 [0.36914797 0.21935931 0.57958533 0.93668102 0.05489795]
 [0.38155332 0.59861046 0.84458302 0.60533035 0.75962275]
 [0.70415288 0.63278637 0.67083566 0.52713592 0.26764396]
 [0.35474438 0.24913334 0.04859349 0.74998357 0.19936106]
 [0.33909439 0.55965851 0.48360216 0.01118009 0.3646447 ]
 [0.13614403 0.34583649 0.71160938 0.28218252 0.07170273]
 [0.40619677 0.23452235 0.01580147 0.74007347 0.75620397]
 [0.30831735 0.07498413 0.97729445 0.99397426 0.10673897]
 [0.33808862 0.8490039  0.40542605 0.8482984  0.15574757]
 [0.73052819 0.7460925  0.57338057 0.13027591 0.32785438]
 [0.04602947 0.97653613 0.86540846 0.75497178 0.35214259]
 [0.07419424 0.93607109 0.57053125 0.97255247 0.9868219 ]
 [0.62089398 0

In [28]:
print(Xm)

[0.4755486  0.5506909  0.50863731 0.48040297 0.49431085]


The command `Xm = np.mean(X,axis=0)` computes the mean of each column which is a `p` dimensional array.  Then, `Xm[None,:]` converts this to a `(1,p)` shape array.  Using Python broadcasting, we can then subtract the `Xm[None,:]` from `X`.

### Example 2:  Standardizing variables

A variant of the above example is to *standardize* the features, where we compute the transform variables,

    Z[i,j] = (X[i,j] - Xm[j])/ Xstd[j]
    
where `Xstd[j]` is the standard deviation per feature.  This can be done as follows:

In [26]:
Xstd = np.std(X,axis=0)
Z = (X-Xm[None,:])/Xstd[None,:]

### Example 3:  Distances

Here is a more complicated example.  Suppose we have a data matrix `X` of shape `(nx,p)` and a second set of points, `Y` of shape `(ny,p)`. For each `i` and `j`, we want to compute the distances, 

     d[i,j] = np.sum((X[i,:] - Y[j,:])**2)
     
This represents the distances between the vectors `X[i,:]` and `Y[j,:]`.  This sort of computation is used for clustering and nearest neighbors.  We can do this without a for loop as follows

In [29]:
# Some random data
nx = 100
ny = 10
p = 2
X = np.random.rand(nx,p)
Y = np.random.rand(ny,p)

# Computing the distances in two lines.  No for loop!
DXY = X[:,None,:]-Y[None,:,:]
d = np.sum(DXY**2,axis=2)

How does this work? First, we use `None` keyword to reshape the matrices `X` and `Y` to compatible sizes

     X[:,None,:]    # Shape nx,  1, p
     Y[None,:,:]    # Shape 1,  ny, p
     
The two matrices can be subtracted so that

     DXY[i,j,k]  = X[i,k] - Y[j,k]
     
Then, `d[i,j] = sum_k (X[i,k] - Y[j,k])**2`, which is the norm squared of the vector differences.

### Example 4:  Outer product

The *outer product* of vectors `x` and `y` is the matrix `Z[i,j] = x[i]y[j]`.  This can be performed in one line as follows

In [30]:
# Some random data
nx = 100
ny = 10
x = np.random.rand(nx)
y = np.random.rand(ny)

# Compute the outer product in one line
Z = x[:,None]*y[None,:]


Here:

     x[:,None] # Has shape (nx,  1)
     y[None,:] # Has shape ( 1, ny)
     
So, with python broadcasting:

     Z = x[:,None]*y[None,:] # has shape (nx,  ny)


**Exercise 1:**  Given a matrix `X`, compute the matrix `Y`, where the rows of `X` are normaized to one.  That is:

     Y[i,j] = X[i,j] / sum_j X[i,j]   

In [32]:
X = np.random.rand(4,3)
# Y = ...
print(X)

[[0.60952311 0.1986837  0.47442406]
 [0.36981251 0.56216677 0.50894898]
 [0.43784007 0.76755036 0.6724187 ]
 [0.88449692 0.2119366  0.31454564]]


In [36]:
sum_j = np.sum(X, axis=1)
print(sum_j)
print(sum_j.shape)

[1.28263087 1.44092826 1.87780913 1.41097916]
(4,)


In [37]:
sum_j = sum_j[:,None]
print(sum_j)

[[1.28263087]
 [1.44092826]
 [1.87780913]
 [1.41097916]]


In [38]:
Y = X / sum_j
print(Y)

[[0.47521319 0.15490325 0.36988355]
 [0.2566488  0.3901421  0.35320911]
 [0.23316537 0.40874781 0.35808682]
 [0.62686746 0.15020533 0.22292721]]


In [40]:
print(np.sum(Y, axis=1))

[1. 1. 1. 1.]


**Exercise 2:** Diagonal multiplication.  Given a matrix `X` and a vector `d`, compute `Y = diag(d)*X`.

In [41]:
X = np.random.rand(5,3)
d = np.random.rand(5)
# Y = ...

In [42]:
print(X)

[[0.98154466 0.16065159 0.51172339]
 [0.21888251 0.45586707 0.25219215]
 [0.39110906 0.89609857 0.68547563]
 [0.63360632 0.64825805 0.38177139]
 [0.133467   0.16797941 0.24072364]]


In [45]:
print(d)

[0.77518652 0.7388749  0.50295973 0.84021186 0.32107665]


In [47]:
D = d[:,None]
print(D)

[[0.77518652]
 [0.7388749 ]
 [0.50295973]
 [0.84021186]
 [0.32107665]]


In [48]:
Y = D*X
print(Y)

[[0.76088019 0.12453495 0.39668107]
 [0.16172679 0.33682874 0.18633845]
 [0.1967121  0.45070149 0.34476663]
 [0.53236355 0.54467411 0.32076885]
 [0.04285314 0.05393427 0.07729074]]
