In [3]:
import numpy as np

# 1-D array

Use `np.arange()` by itself to create a 1-D array: 

In [4]:
a = np.arange(10)
b = np.arange(3,11)
c = np.arange(4,12,dtype=float)
d = np.arange(2,3,0.25)

print(a, b , c, d, sep='\n\n')

[0 1 2 3 4 5 6 7 8 9]

[ 3  4  5  6  7  8  9 10]

[ 4.  5.  6.  7.  8.  9. 10. 11.]

[2.   2.25 2.5  2.75]


use `shape` attribute of an array to find its dimensions

In [20]:
print(a.shape)

(10,)


**(,n) is not a valid shape**

# 2-D array

Use `np.reshape()` on a 1d array to create a 2d array:

In [27]:
a2row = a.reshape(1,10)
a2col = a.reshape(10,1)

print(a2row, a2col, sep='\n\n')

[[0 1 2 3 4 5 6 7 8 9]]

[[0]
 [1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]
 [9]]


In the above code, we created a 10x1 (10 rows and 1 column) matrix a2col and a 1x10 matrix a2row

We can always reshape an array as many times as we want.

In [7]:
print(a2row.reshape(2,5))

[[0 1 2 3 4]
 [5 6 7 8 9]]


In [9]:
print(a2row.reshape(2,5).reshape(5,2))

[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


# Axis DNE error:

In [8]:
print(a.shape)
print(np.sum(a, axis=1))


(10,)


AxisError: axis 1 is out of bounds for array of dimension 1

array a is 1-D, it only has one axis, axis 0.

# Matrix multiplication vs. element-by-element multiplication:

## matrix multiplication:

In [21]:
A = np.arange(3, 11).reshape(2,4)
B = np.arange(1,8,2).reshape(2,2)

print(A, B, sep='\n\n')

[[ 3  4  5  6]
 [ 7  8  9 10]]

[[1 3]
 [5 7]]


Use `@`:

In [22]:
print(B@A)

[[ 24  28  32  36]
 [ 64  76  88 100]]


## element-by-element multiplication:

the two arrays to be multiplied must have the same shape

Use `*`:

In [23]:
print(B*B)
print(A*A)

[[ 1  9]
 [25 49]]
[[  9  16  25  36]
 [ 49  64  81 100]]


# Custom array:

Use `np.array()`:

In [24]:
my1D = np.array([1, 2, 3])
my2D = np.array([[1, 6, 7], [2, 6, 0], [1, 4, 5]]) # 3 x 3 array. Separate elements and rows with ,

print(my1D, my2D, sep='\n\n')

[1 2 3]

[[1 6 7]
 [2 6 0]
 [1 4 5]]


## Broadcasting example:

`my1D` is stretched to a 3 x 3 array: and multiplied element wise with `my2D`:

In [25]:
print(my1D*my2D)

[[ 1 12 21]
 [ 2 12  0]
 [ 1  8 15]]


# Shape of constants (i.e. scalars)

In [31]:
num = np.array(2)
print(num)
print(num.shape)

2
()


constants (not even contained in an array) have no shape

# Accessing elements in 1-D array:

In [32]:
arr = np.array([10, 20, 30, 40, 50])

Use the slice syntax `[:]`

`arr[:]` returns the entire array

In [33]:
print(arr[:])

[10 20 30 40 50]


`arr[a:b]` returns every element from index `a` up to (but not including) index `b`:

In [34]:
print(arr[1:4])

[20 30 40]


`arr[:b]` accesses from start up to index b: 

In [35]:
print(arr[:4])

[10 20 30 40]


`arr[2:]` accesses from index `2` to the end:

In [ ]:
print(arr[2:])

[30 40 50]


In [45]:
arr2 = np.arange(2,80,3)
print(arr2)
print(arr2.shape)

[ 2  5  8 11 14 17 20 23 26 29 32 35 38 41 44 47 50 53 56 59 62 65 68 71
 74 77]
(26,)


`arr[::b]`, where `b` is a positive integer, accesses every `b`th element in the array:

In [55]:
print(arr2[::13])

[ 2 41]


`arr[::-1]` reverses the list:

In [56]:
print(arr2[::-1])

[77 74 71 68 65 62 59 56 53 50 47 44 41 38 35 32 29 26 23 20 17 14 11  8
  5  2]


Examples shown above about splicing can be combined:

Example1: Reverse and select every 3rd element from the array:

In [57]:
print(arr2[::-3])

[77 68 59 50 41 32 23 14  5]


Example2: starting from the element at index 20, select every 5th element backwards up to the one at index 5.

`arr2[20]`, `arr2[15]`, and `arr2[10]` were selected

In [62]:
print(arr2[20:5:-5])

[62 47 32]


**General splicing format is `array[start: stop: step]`**

With a positive step, start < stop is required to get values.

With a negative step, start > stop is required to get values.

Otherwise → empty result.

In [64]:
print(arr2[5:20:-2])

[]


# Accessing elements in multidimensional array:

In [70]:
arr = np.arange(1,25).reshape(6,4)
arr = np.array(arr)
print(arr)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]
 [17 18 19 20]
 [21 22 23 24]]


For the most basic case (2-D array), each element of `arr` is one single row

In [75]:
print(arr[2:]) # Get all elements starting at index 2

[[ 9 10 11 12]
 [13 14 15 16]
 [17 18 19 20]
 [21 22 23 24]]


We use mult-axis slicing with commas as follows:

`arr[:,a]` accesses all rows (`:`), column at index `a`:

In [72]:
print(arr[:,2])

[ 3  7 11 15 19 23]


`arr[a,:]` accesses row `a`, all columns (`:`)

In [ ]:
print(arr[3,:])

[13 14 15 16]


`arr[:,:]` accesses all rows (`:`), all columns (`:`)

In [74]:
print(arr[:,:])

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]
 [17 18 19 20]
 [21 22 23 24]]


`arr[a:,:d]` accesses all rows starting at `a`, and all columns up to index `b`:

In [77]:
print(arr[4:,:2])

[[17 18]
 [21 22]]


`arr[a:b,c:d]` accesses rows starting at `a` up to `b`, and columns starting at `c` up to `d`:

In [78]:
print(arr[2:4,1:3])

[[10 11]
 [14 15]]


the splicing rule of `start: stop: step` can be used in combination with multidimensional splicing:

In [80]:
print(arr[::2,1::2])

[[ 2  4]
 [10 12]
 [18 20]]


Access every 2nd row starting from 0, and for each row selected, starting at column 1, take every 2nd column

# Python list vs NumPy Array

## Python list:

- General purpose container
- Can hold different types of objects in the same list:

In [87]:
arr = [10, 'hello', 3.14, [1, 2]]

Operations are **element-wise in terms of objects**, not math:

In [ ]:
print(arr*2) # list repetition twice, not multiplication by 2

[10, 'hello', 3.14, [1, 2], 10, 'hello', 3.14, [1, 2]]


In [89]:
arr = arr + ['a', 'b', 'c'] # concatnation to arr
print(arr)

[10, 'hello', 3.14, [1, 2], 'a', 'b', 'c']


## NumPy Array: 

- All elements are stored in the same data type, usually numeric

In [93]:
np_arr = np.array([1, 2, 3])
np_arr2 = np.array([5, 9, 9], dtype=float)

print(np_arr + np_arr2) # element-wise addition
print(3*np_arr) # scalar multiplication by 3

[ 6. 11. 12.]
[3 6 9]


## Trick to turn a row vector into a column vector:

In [144]:
num = np.random.randint(5,25)
a = np.arange(1,num)
print(a)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14]


Use `a[:, np.newaxis]`

- `:`→ means “take all elements along this axis” (so far the same as slicing).

- `np.newaxis` (which is just `None`) is not a slice, but a way of inserting a new dimension.

What we are telling Python to do is:
- “Keep all rows (`:`), and in the next axis that I just created (`np.newaxis`), put them as columns.”

In short, we turn a `(4,)` array into a `(4,1)` one.

In [145]:
print(a[:, np.newaxis])

[[ 1]
 [ 2]
 [ 3]
 [ 4]
 [ 5]
 [ 6]
 [ 7]
 [ 8]
 [ 9]
 [10]
 [11]
 [12]
 [13]
 [14]]
