In [3]:
import numpy as np

In [4]:
a = np.array([[1, 2, 3],
              [4, 5, 6]])   # shape (2, 3)
b = np.array([[10, 20, 30, 40, 50]])  # shape (1, 5)

print(a + b)


ValueError: operands could not be broadcast together with shapes (2,3) (1,5) 

## BroadCasting

In [5]:

test = np.array([[[[2],[6]]], [[[2],[6]]], [[[2],[6]]]])
test2 = np.array([[[8,-1]],[[8,-1]],[[8,-1]]])

print(test.shape)
print(test2.shape)


(3, 1, 2, 1)
(3, 1, 2)


In [6]:
C = np.array([2, 2])
D = np.array([[8],[-1]])

print(C*D)

[[16 16]
 [-2 -2]]


In [7]:
print(test*test2)

[[[[16 -2]
   [48 -6]]

  [[16 -2]
   [48 -6]]

  [[16 -2]
   [48 -6]]]


 [[[16 -2]
   [48 -6]]

  [[16 -2]
   [48 -6]]

  [[16 -2]
   [48 -6]]]


 [[[16 -2]
   [48 -6]]

  [[16 -2]
   [48 -6]]

  [[16 -2]
   [48 -6]]]]


## Dimensions (tensors)

In [9]:
square = np.array([[[[1, 1],[1,1]], [[1, 1],[1,1]]],[[[1, 1],[1,1]], [[1, 1],[1,1]]]])
print(square)
print(square.shape)

[[[[1 1]
   [1 1]]

  [[1 1]
   [1 1]]]


 [[[1 1]
   [1 1]]

  [[1 1]
   [1 1]]]]
(2, 2, 2, 2)


In [11]:
a = np.array(1)
b = np.array([1])
c = np.array([[1]])
d = np.array([[[1]]])
print(a.shape, b.shape, c.shape, d.shape)

() (1,) (1, 1) (1, 1, 1)


## using `np.sum`

In [62]:
a = np.array([[1,2],[3,4],[5,6]])
print(np.sum(a, axis=1))


[ 3  7 11]


## Generate random 4 row array:

In [57]:
num_col = np.random.randint(5,25)
A = np.arange(1, 4*num_col + 1).reshape(4, num_col)
print(A)

[[ 1  2  3  4  5  6  7  8  9 10]
 [11 12 13 14 15 16 17 18 19 20]
 [21 22 23 24 25 26 27 28 29 30]
 [31 32 33 34 35 36 37 38 39 40]]


## For loop review:

In [61]:
for i in range(7):
    print('check', i)

check 0
check 1
check 2
check 3
check 4
check 5
check 6


## summing tensor by axis:

In [71]:
X = np.arange(1,13).reshape(1,3,2,2)
print(X)

[[[[ 1  2]
   [ 3  4]]

  [[ 5  6]
   [ 7  8]]

  [[ 9 10]
   [11 12]]]]


In [72]:
print(np.sum(X,axis=0))

[[[ 1  2]
  [ 3  4]]

 [[ 5  6]
  [ 7  8]]

 [[ 9 10]
  [11 12]]]


In [74]:
print(np.sum(X,axis=1))

[[[15 18]
  [21 24]]]


In [76]:
print(np.sum(X,axis=2))

[[[ 4  6]
  [12 14]
  [20 22]]]


In [77]:
print(np.sum(X,axis=3))

[[[ 3  7]
  [11 15]
  [19 23]]]


## Reshaping:

In [79]:
a = np.arange(5)
print(a)
print(a[None,:])

[0 1 2 3 4]
[[0 1 2 3 4]]


## Adding new dimension:

In [80]:
X = np.arange(6).reshape(3,2)
X

array([[0, 1],
       [2, 3],
       [4, 5]])

In [81]:
X[:, :, None]

array([[[0],
        [1]],

       [[2],
        [3]],

       [[4],
        [5]]])