In [43]:
import numpy as np

In [44]:
a = np.array([[1, 2, 3],
              [4, 5, 6]])   # shape (2, 3)
b = np.array([[10, 20, 30, 40, 50]])  # shape (1, 5)

#print(a + b)


## BroadCasting

In [45]:

test = np.array([[[[2],[6]]], [[[2],[6]]], [[[2],[6]]]])
test2 = np.array([[[8,-1]],[[8,-1]],[[8,-1]]])

print(test.shape)
print(test2.shape)


(3, 1, 2, 1)
(3, 1, 2)


In [46]:
C = np.array([2, 2])
D = np.array([[8],[-1]])

print(C*D)

[[16 16]
 [-2 -2]]


In [47]:
print(test*test2)

[[[[16 -2]
   [48 -6]]

  [[16 -2]
   [48 -6]]

  [[16 -2]
   [48 -6]]]


 [[[16 -2]
   [48 -6]]

  [[16 -2]
   [48 -6]]

  [[16 -2]
   [48 -6]]]


 [[[16 -2]
   [48 -6]]

  [[16 -2]
   [48 -6]]

  [[16 -2]
   [48 -6]]]]


## Dimensions (tensors)

In [48]:
square = np.array([[[[1, 1],[1,1]], [[1, 1],[1,1]]],[[[1, 1],[1,1]], [[1, 1],[1,1]]]])
print(square)
print(square.shape)

[[[[1 1]
   [1 1]]

  [[1 1]
   [1 1]]]


 [[[1 1]
   [1 1]]

  [[1 1]
   [1 1]]]]
(2, 2, 2, 2)


In [49]:
a = np.array(1)
b = np.array([1])
c = np.array([[1]])
d = np.array([[[1]]])
print(a.shape, b.shape, c.shape, d.shape)

() (1,) (1, 1) (1, 1, 1)


## using `np.sum`

In [50]:
a = np.array([[1,2],[3,4],[5,6]])
print(np.sum(a, axis=1))


[ 3  7 11]


## Generate random 4 row array:

In [51]:
num_col = np.random.randint(5,25)
A = np.arange(1, 4*num_col + 1).reshape(4, num_col)
print(A)

[[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38]
 [39 40 41 42 43 44 45 46 47 48 49 50 51 52 53 54 55 56 57]
 [58 59 60 61 62 63 64 65 66 67 68 69 70 71 72 73 74 75 76]]


## For loop review:

In [52]:
for i in range(7):
    print('check', i)

check 0
check 1
check 2
check 3
check 4
check 5
check 6


## summing tensor by axis:

In [53]:
X = np.arange(1,13).reshape(1,3,2,2)
print(X)

[[[[ 1  2]
   [ 3  4]]

  [[ 5  6]
   [ 7  8]]

  [[ 9 10]
   [11 12]]]]


In [54]:
print(np.sum(X,axis=0))

[[[ 1  2]
  [ 3  4]]

 [[ 5  6]
  [ 7  8]]

 [[ 9 10]
  [11 12]]]


In [55]:
print(np.sum(X,axis=1))

[[[15 18]
  [21 24]]]


In [56]:
print(np.sum(X,axis=2))

[[[ 4  6]
  [12 14]
  [20 22]]]


In [57]:
print(np.sum(X,axis=3))

[[[ 3  7]
  [11 15]
  [19 23]]]


## Reshaping:

In [58]:
a = np.arange(5)
print(a)
print(a[None,:])

[0 1 2 3 4]
[[0 1 2 3 4]]


## Adding new dimension:

In [59]:
X = np.arange(6).reshape(3,2)
X

array([[0, 1],
       [2, 3],
       [4, 5]])

In [60]:
X[:, :, None]

array([[[0],
        [1]],

       [[2],
        [3]],

       [[4],
        [5]]])

## Latex

### Keyboard shortcut to add markdown: (B) for below + (M) for Markdown.

$$y_i = \beta_0 + \beta_1 x_{i1} + \beta_2 x_{i2} + \epsilon_i$$

$$X = \begin{pmatrix} 1 & x_{11} & x_{12} \\ 1 & x_{21} & x_{22} \\ 1 & x_{31} & x_{32} \\ 1 & x_{41} & x_{42} \end{pmatrix}$$

$$X = \begin{pmatrix} 1 & 0 & 1 \\ 1 & 2 & 3 \\ 1 & 4 & 8 \\ 1 & 6 & 10 \end{pmatrix}$$

$$\mathbf{y} = \begin{pmatrix} 3.0 \\ 5.0 \\ 9.0 \\ 10.0 \end{pmatrix} ,  \mathbf{\beta} = \begin{pmatrix} \beta_0 \\ \beta_1 \\ \beta_2 \end{pmatrix}$$

$$\mathbf{\beta} = (X^T X)^{-1} X^T \mathbf{y}$$

$$\mathbf{X} = \begin{pmatrix} 1 & 0 & 1 \\ 1 & 2 & 3 \\ 1 & 4 & 8 \\ 1 & 6 & 10 \end{pmatrix}$$

In [61]:
dtest = np.arange(1,11)
dtest_1 = np.array(range(1,11))

In [62]:
dtest

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [63]:
dtest_1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [64]:
u = np.arange(1,20,2)
print(u)
x = np.zeros(len(u))
print(x)
print(np.ones(len(u))*np.exp(1))

[ 1  3  5  7  9 11 13 15 17 19]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[2.71828183 2.71828183 2.71828183 2.71828183 2.71828183 2.71828183
 2.71828183 2.71828183 2.71828183 2.71828183]


In [71]:
d = 1
r = u * np.arange(d+1)[:, None]
y_hat = np.exp((u * np.arange(d+1)[:, None])/-d)
print(r)
print(y_hat)
print(np.sum(y_hat,axis=0))
print(u)

[[ 0  0  0  0  0  0  0  0  0  0]
 [ 1  3  5  7  9 11 13 15 17 19]]
[[1.00000000e+00 1.00000000e+00 1.00000000e+00 1.00000000e+00
  1.00000000e+00 1.00000000e+00 1.00000000e+00 1.00000000e+00
  1.00000000e+00 1.00000000e+00]
 [3.67879441e-01 4.97870684e-02 6.73794700e-03 9.11881966e-04
  1.23409804e-04 1.67017008e-05 2.26032941e-06 3.05902321e-07
  4.13993772e-08 5.60279644e-09]]
[1.36787944 1.04978707 1.00673795 1.00091188 1.00012341 1.0000167
 1.00000226 1.00000031 1.00000004 1.00000001]
[ 1  3  5  7  9 11 13 15 17 19]
