In [1]:
import numpy as np

## 6a

In [2]:
X = np.zeros(16)
for i in range(16):
    X[i] = np.random.randint(-5,25)
X = X.reshape(4,4)
print(X)

[[21. -5. -3. 13.]
 [10.  6.  0. -5.]
 [21. -1. 19. -3.]
 [-1.  5. 21.  9.]]


In [3]:
beta = np.array([1, 2, 3])

Given a data matrix X and vector beta compute a vector yhat:

In [4]:
n = X.shape[0]
yhat = np.zeros(n)
for i in range(n):
    yhat[i] = beta[0]*X[i ,0] + beta[1]*X[i ,1] + beta[2]*X[i,1]*X[i ,2]

In [5]:
print(yhat)

[ 56.  22. -38. 324.]


### 6a solution:

In [6]:
Y_hat = beta[0]*X[:,0] + beta[1]*X[:,1] + beta[2]*X[:,1]*X[:,2]
print(Y_hat)

[ 56.  22. -38. 324.]


## 6b

Given vectors x, alpha, and beta computes a vector yhat:

In [68]:
x = np.random.rand(5)
alpha = np.random.rand(12)
beta = np.random.rand(15)

In [69]:
print('x: ', x, 'alpha: ', alpha, 'beta: ', beta, sep='\n\n')

x: 

[0.51065132 0.25711142 0.55927761 0.1756901  0.89582091]

alpha: 

[0.6584613  0.11364529 0.83337562 0.91934919 0.32786096 0.14861485
 0.40203831 0.31386583 0.41768581 0.17100189 0.65595622 0.05784323]

beta: 

[0.54040347 0.63875099 0.65387188 0.5182971  0.37404857 0.5037947
 0.75427893 0.11554373 0.50673575 0.3176577  0.9052506  0.50824383
 0.6888244  0.55255891 0.58643902]


In [70]:
n = len(x)
m = len(alpha)
yhat = np.zeros(n)
for i in range(n):
    for j in range(m):
        yhat[i] += alpha[j] * np.exp(-beta[j] * x[i]) # beta should have at least as many elements as alpha

In [71]:
print(yhat)

[3.76483917 4.33749917 3.66500544 4.54163193 3.05057423]


### 6b solution:

In [72]:
Y_hat = np.sum(alpha[:, None] * np.exp(-1 * beta[:len(alpha), None] * x), axis=0)
print(Y_hat)

[3.76483917 4.33749917 3.66500544 4.54163193 3.05057423]


## 6c

Given arrays x and y, find the squared distances dist:

In [154]:
row_x = np.random.randint(2, 10)   
col = np.random.randint(2, 10) 
row_y = np.random.randint(2, 10)   

x = np.random.randint(-20, 21, size=(row_x, col))
y = np.random.randint(-20, 21, size=(row_y, col))

print(x,y,sep='\n\n')

[[ 12   2]
 [ -6   1]
 [  2 -12]
 [  5  -6]]

[[  0 -15]
 [ 10 -17]
 [ 15  18]
 [ 19  -2]
 [ 11   7]
 [ 11 -19]
 [-11  18]]


In [155]:
n,d = x.shape
m,d = y.shape
dist = np.zeros((n,m))
for i in range(n):
    for j in range(m):
        for k in range(d):
            dist[i,j] += (x[i,k] - y[j,k])**2 # x and y need to have the same number of columns

In [156]:
print(dist)

[[ 433.  365.  265.   65.   26.  442.  785.]
 [ 292.  580.  730.  634.  325.  689.  314.]
 [  13.   89. 1069.  389.  442.  130. 1069.]
 [ 106.  146.  676.  212.  205.  205.  832.]]


### 6c solution:

In [157]:
Dist = ((x[:, None, :] - y[None, :, :])**2).sum(axis=2)
print(Dist)

[[ 433  365  265   65   26  442  785]
 [ 292  580  730  634  325  689  314]
 [  13   89 1069  389  442  130 1069]
 [ 106  146  676  212  205  205  832]]
