In [1]:
import numpy as np

## 6a

In [2]:
X = np.zeros(16)
for i in range(16):
    X[i] = np.random.randint(-5,25)
X = X.reshape(4,4)
print(X)

[[15. 15. 16. 24.]
 [-2. 18. -3.  5.]
 [ 4. 22.  0. 16.]
 [ 1.  5. 14.  6.]]


In [3]:
beta = np.array([1, 2, 3])

Given a data matrix X and vector beta compute a vector yhat:

In [4]:
n = X.shape[0]
yhat = np.zeros(n)
for i in range(n):
    yhat[i] = beta[0]*X[i ,0] + beta[1]*X[i ,1] + beta[2]*X[i,1]*X[i ,2]

In [5]:
print(yhat)

[ 765. -128.   48.  221.]


### 6a solution:

In [6]:
Y_hat = beta[0]*X[:,0] + beta[1]*X[:,1] + beta[2]*X[:,1]*X[:,2]
print(Y_hat)

[ 765. -128.   48.  221.]


## 6b

Given vectors x, alpha, and beta computes a vector yhat:

In [7]:
x = np.random.rand(5)
alpha = np.random.rand(12)
beta = np.random.rand(15)

In [8]:
print('x: ', x, 'alpha: ', alpha, 'beta: ', beta, sep='\n\n')

x: 

[0.28020617 0.77647552 0.08130866 0.67919952 0.22235802]

alpha: 

[0.02644249 0.63400114 0.28186378 0.93849429 0.08946507 0.22324837
 0.27381436 0.7205751  0.59452168 0.8504871  0.15570075 0.43584123]

beta: 

[0.28144372 0.16668816 0.1929249  0.52312921 0.91285335 0.63063005
 0.76346277 0.00216364 0.74953807 0.32099226 0.07287192 0.4939513
 0.19779123 0.11901025 0.38512556]


In [9]:
n = len(x)
m = len(alpha)
yhat = np.zeros(n)
for i in range(n):
    for j in range(m):
        yhat[i] += alpha[j] * np.exp(-beta[j] * x[i]) # beta should have at least as many elements as alpha

In [10]:
print(yhat)

[4.69593851 3.93691758 5.06254976 4.07023089 4.79845123]


### 6b solution:

In [11]:
Y_hat = np.sum(alpha[:, None] * np.exp(-1 * beta[:len(alpha), None] * x), axis=0)
print(Y_hat)

[4.69593851 3.93691758 5.06254976 4.07023089 4.79845123]


## 6c

Given arrays x and y, find the squared distances dist:

In [13]:
row_x = np.random.randint(2, 10)   
col = np.random.randint(2, 10) 
row_y = np.random.randint(2, 10)   

x = np.random.randint(-20, 21, size=(row_x, col))
y = np.random.randint(-20, 21, size=(row_y, col))

print(x,y,sep='\n\n')

[[ 11   1 -14   1  -5   8  -9  -3]
 [ 17  -1   4 -20  18   0   7   4]
 [ -7  -6  13  12   9 -12   9  -8]
 [ 17  14   9 -15 -16 -17  11   8]]

[[-18   2  15 -16   1   8  13 -16]
 [  5  -9 -20   2   4   6   6 -15]
 [  6 -11  -8  16   7   0  10   8]
 [ -3  19 -17 -14  -4 -18  -7  12]
 [-15 -14   0  -6  12  10  10  -6]
 [ 13 -10  -4 -17  -6   4 -17   0]]


In [14]:
n,d = x.shape
m,d = y.shape
dist = np.zeros((n,m))
for i in range(n):
    for j in range(m):
        for k in range(d):
            dist[i,j] += (x[i,k] - y[j,k])**2 # x and y need to have the same number of columns

In [15]:
print(dist)

[[2661.  627. 1120. 1660. 1809.  639.]
 [2160. 1862. 1807. 2345. 1650. 1354.]
 [1517. 1749. 1056. 3078. 1119. 2767.]
 [2900. 3286. 2815. 1587. 3680. 2154.]]


### 6c solution:

In [16]:
Dist = ((x[:, None, :] - y[None, :, :])**2).sum(axis=2)
print(Dist)

[[2661  627 1120 1660 1809  639]
 [2160 1862 1807 2345 1650 1354]
 [1517 1749 1056 3078 1119 2767]
 [2900 3286 2815 1587 3680 2154]]


In [17]:
Dist2 = ((x[None, :, :] - y[:, None, :])**2).sum(axis=2)
print(Dist2)

[[2661 2160 1517 2900]
 [ 627 1862 1749 3286]
 [1120 1807 1056 2815]
 [1660 2345 3078 1587]
 [1809 1650 1119 3680]
 [ 639 1354 2767 2154]]
